--
-- ノート関連チームテーブル作成
--
CREATE TABLE IF NOT EXISTS note_teams (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ノート関連チームID',
    note_id INT(11) NOT NULL COMMENT 'ノートID',
    team_id INT(11) NOT NULL COMMENT 'チームID',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
);
