--
-- ノート関連タグテーブル作成
--
CREATE TABLE IF NOT EXISTS note_tags (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ノート関連タグID',
    note_id INT(11) NOT NULL COMMENT 'ノートID',
    tag_id INT(11) NOT NULL COMMENT 'タグID',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
);
