--
-- タグテーブル作成
--
CREATE TABLE IF NOT EXISTS tags (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'タグID',
    name VARCHAR(20) NOT NULL COMMENT 'タグ名',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
);
