--
-- チームテーブル作成
--
CREATE TABLE IF NOT EXISTS teams (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'チームID',
    name VARCHAR(50) NOT NULL COMMENT 'チーム名',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
);
